# Makefile for Java port of GNU getopt

all: 
	javac -AuseConservativeDefaultsForUnannotatedSourceCode LongOpt.java Getopt.java GetoptDemo.java

docs: 
	javadoc -author -version -public Getopt.java LongOpt.java
